name: hoop-io-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - pip
  
  # Node.js for frontend
  - nodejs=20
  
  # Jupyter and proxy for web access
  - jupyter
  - jupyter-server-proxy
